#!/usr/bin/env python3
"""Export what a front end needs from the contracts as they are RIGHT NOW: one ABI json per contract, and a Markdown
table of every user-facing function and event with its selector / topic0.

  tools/export_abi.py [out_dir]          # default: abi/

Generated, never hand-edited -- the contracts change between releases (the singleton hook keys everything by PoolId
where the per-launch hook took no argument), and a hand-written ABI is the one that is wrong on launch day. Re-run it
on the commit that is actually deployed and ship that output with the front end.
"""
import json, os, subprocess, sys

CONTRACTS = ['HedgeFunFactory', 'HedgeFunHook', 'HedgeFunV2Hook', 'HedgeFunTreasury', 'HedgeFunToken', 'HedgeFunTradeRouter', 'HedgeFunLaunchRouter', 'PriceOracle', 'TradingCalendar',
             'HedgeFunV2Factory', 'CurveDeployer', 'HedgeFunBondingCurve', 'HedgeFunV2Treasury', 'HedgeFunV2AllInTreasury', 'HedgeFunV2EngineTreasury', 'V2RebalancePolicy', 'V2TreasuryDeployer',
             'V2LiquidityVault', 'HedgeFunV2TradeRouter', 'HedgeFunV2NativeRouter', 'HedgeFunV2LaunchNativeRouter',
             'HedgeFunV2AssetPercentEngineTreasury', 'V2FundAssetReader', 'V2AssetPercentRebalancePolicy']
PLUMBING = {'unlockCallback', 'uniswapV3SwapCallback', 'afterSwap', 'beforeSwap', 'beforeInitialize', 'afterInitialize', 'beforeAddLiquidity', 'afterAddLiquidity',
            'beforeRemoveLiquidity', 'afterRemoveLiquidity', 'beforeDonate', 'afterDonate', 'payStock', 'settleStock', 'settleToken', 'bind', 'register', 'registerGraduated', 'graduateCurve', 'release', 'wire'}

def typ(i): return '(' + ','.join(typ(c) for c in i['components']) + ')' + i['type'][5:] if i['type'].startswith('tuple') else i['type']
def sig(x): return x['name'] + '(' + ','.join(typ(i) for i in x['inputs']) + ')'
def keccak(s): return subprocess.check_output(['cast', 'keccak', s]).decode().strip()

def main():
    out = sys.argv[1] if len(sys.argv) > 1 else 'abi'; os.makedirs(out, exist_ok=True)
    commit = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD']).decode().strip()
    md = ['# Contract surface for a front end', '', 'Generated by `tools/export_abi.py` at commit `%s`. Do not edit; re-run.' % commit, '']
    for c in CONTRACTS:
        try: abi = json.loads(subprocess.check_output(['forge', 'inspect', c, 'abi', '--json'], stderr=subprocess.DEVNULL))
        except Exception: continue
        json.dump(abi, open(os.path.join(out, c + '.json'), 'w'), indent=1)
        fns = [x for x in abi if x['type'] == 'function' and x['name'] not in PLUMBING]
        md += ['## %s' % c, '', '| kind | signature | selector / topic0 | returns |', '|---|---|---|---|']
        for x in sorted(fns, key=lambda x: (x['stateMutability'] in ('view', 'pure'), x['name'])):
            kind = 'read' if x['stateMutability'] in ('view', 'pure') else ('write, payable' if x['stateMutability'] == 'payable' else 'write')
            md.append('| %s | `%s` | `%s` | %s |' % (kind, sig(x), keccak(sig(x))[:10], ', '.join('`%s`' % typ(o) for o in x['outputs']) or ''))
        for x in sorted((x for x in abi if x['type'] == 'event'), key=lambda x: x['name']):
            args = ', '.join(('%s %s%s' % (typ(i), 'indexed ' if i['indexed'] else '', i['name'])) for i in x['inputs'])
            md.append('| event | `%s(%s)` | `%s` | |' % (x['name'], args, keccak(sig(x))))
        md.append('')
    open(os.path.join(out, 'SURFACE.md'), 'w').write('\n'.join(md)); print('wrote', out + '/', 'at', commit)

if __name__ == '__main__': main()
